let express = require('express');
let router = express.Router();
let controller = require('../Controllers/UserController');
let isAdmin = require('../Middleware/isAdmin');
router.post('/user', controller.register);
router.get('/' ,  controller.auth, controller.getAll);
router.get('/:id',  controller.getById);
router.delete('/:id',  controller.deleteById);
router.put('/:id',  controller.updateById);
router.post('/login', controller.login);
module.exports = router;